source "https://rubygems.org"

ruby ">= 3.2"

gem "base64"
gem "bigdecimal", "~> 3.1"
gem "ed25519", "~> 1.4"
gem "puma", "~> 8.0"
gem "rack", "~> 3.2"
gem "roda", "~> 3.108"
gem "sequel", "~> 5.0"
gem "sqlite3", "~> 2.0"

group :development, :test do
  gem "minitest", "~> 5.20"
  gem "rack-test", "~> 2.2"
  gem "rake", "~> 13.0"
end
