# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:spec) do |t|
  t.libs << "lib" << "spec" << "spec/support"
  t.test_files = FileList["spec/**/*_spec.rb"]
  t.warning = false
end

desc "Show this server's host account, creating it if this is the first run"
task :host do
  $LOAD_PATH.unshift File.expand_path("lib", __dir__)
  require "agnostic/server"
  server = Agnostic::Server.new
  puts JSON.pretty_generate(server.host.to_h.reject { |k, _| k == "declaration" })
end

task default: :spec
